import type { Metadata } from "next";
import { Yeseva_One, Varela_Round } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Footer from "@/components/Footer";
import AuthProvider from "@/context/AuthProvider";
import { ImageKitProvider } from "@imagekit/next";
import { CartProvider } from "@/context/CartContext";
import { PageProvider } from "@/context/PageContext";
import ContentManager from "@/components/ContentManager";
import NavbarSwitcher from "@/components/NavbarSwitcher";
import StoreStatusBanner from "@/components/global/StoreStatusBanner";

export const metadata: Metadata = {
  title: "Luminous Bistro - Illuminate Your Taste Buds",
  description: "Generated by Waqar Rajpoot",
  verification: {
    google: "EV6RljGRrr8-cuXJ19J964MR7MVS0RS09CugbgMufhg",
  },
};
// Configure the Yeseva One font
const yesevaOne = Yeseva_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-yeseva-one",
  display: "swap",
});

// Configure the Varela Round font
const varelaRound = Varela_Round({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-varela-round",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${yesevaOne.variable} ${varelaRound.variable}`}
        cz-shortcut-listen="true"
      >
        <AuthProvider>
          <ImageKitProvider
            urlEndpoint={process.env.NEXT_PUBLIC_IMAGEKIT_URL_ENDPOINT}
          >
            <CartProvider>
              <PageProvider>
                <NavbarSwitcher />
                <StoreStatusBanner />
                <ContentManager>{children}</ContentManager>
                <Footer />
                <Toaster />
              </PageProvider>
            </CartProvider>
          </ImageKitProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
